# Generated by Django 2.0.7 on 2018-07-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0003_auto_20180706_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
